# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jointeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_teams', to='jointeam2.Teams')),
                ('all_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_users', to='jointeam.Users')),
            ],
        ),
    ]
