-- MySQL Script generated by MySQL Workbench
-- Tue May 16 11:51:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Books` DEFAULT CHARACTER SET utf8 ;
USE `Books` ;

-- -----------------------------------------------------
-- Table `Books`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `users_id` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_books_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Books`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`fave_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`fave_books` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fave_books_users1_idx` (`user_id` ASC),
  INDEX `fk_fave_books_books1_idx` (`book_id` ASC),
  CONSTRAINT `fk_fave_books_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Books`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fave_books_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `Books`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Books`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `users_id` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_books_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Books`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
