# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_start', models.DateField()),
                ('travel_end', models.DateField()),
                ('plan', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='join',
            name='all_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everything', to='blackbelt.Travel'),
        ),
        migrations.AddField(
            model_name='join',
            name='all_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='everyone', to='login.User'),
        ),
    ]
