# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('blackbelt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='user_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
